name: Deploy To Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy To Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/checkout@v4
        with:
          node-version: 21.x

      - name: Install dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Deploy to Render
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
